// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesL9XLfBbBQzHWDSEfdxoDVdHfLQBfoE',
    appId: '1:985903147677:web:da74cab54db8aa66d84274',
    messagingSenderId: '985903147677',
    projectId: 'baraton-stores',
    authDomain: 'baraton-stores.firebaseapp.com',
    storageBucket: 'baraton-stores.appspot.com',
    measurementId: 'G-ZF4FFN3MCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBHzaY5JHt0KEg0gN8ypkZMC9ENsArJYc',
    appId: '1:985903147677:android:0dcd7735b0089463d84274',
    messagingSenderId: '985903147677',
    projectId: 'baraton-stores',
    storageBucket: 'baraton-stores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOViQHTYZRLhPnImrUoOFqt7AB-b26Uk',
    appId: '1:985903147677:ios:a0cfa8c92a378a56d84274',
    messagingSenderId: '985903147677',
    projectId: 'baraton-stores',
    storageBucket: 'baraton-stores.appspot.com',
    iosClientId: '985903147677-cf7rij7infa7qiqphqd76updb4gsp46o.apps.googleusercontent.com',
    iosBundleId: 'com.example.baratonStores',
  );
}
